# To use Solr 9 locally: cp docker-compose.override-solr-9.yml docker-compose.override.yml
services:
  solr:
    image: ghcr.io/samvera-labs/hyku_knapsack/solr:${TAG:-latest}-9
    build:
      args:
        SOLR_VERSION: ${SOLR_VERSION:-9}
    environment:
      - SOLR_OPTS=${SOLR_OPTS--Dsolr.config.lib.enabled=true -Dsolr.filterCache.class=solr.CaffeineCache -Dsolr.queryResultCache.class=solr.CaffeineCache -Dsolr.documentCache.class=solr.CaffeineCache}
